version: "3"

services:
  hive-db-metastore:
    image: postgres:15.4-alpine3.18
    container_name: fbnet-hive-db-metastore
    hostname: hive-db-metastore
    networks:
      - fbnet-hadoop
    restart: always
    volumes:
      - hive_db_metastore:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  
  hive-metastore:
    image: fcjbispo/fbnet-hive:3.1.3-hadoop3.3.6-java8
    container_name: fbnet-hive-metastore
    hostname: hive-metastore
    networks:
      - fbnet-hadoop
    restart: always
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "hive-db-metastore:5432"
    ports:
      - "9083:9083"

  hive-server:
    image: fcjbispo/fbnet-hive:3.1.3-hadoop3.3.6-java8
    container_name: fbnet-hive-server
    hostname: hive-server
    networks:
      - fbnet-hadoop
    restart: always
    env_file:
      - ./hadoop-hive.env
    environment:
      CORE_CONF_fs_defaultFS: "namenode:9000"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-db-metastore/postgres"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  
volumes:
  hive_db_metastore:
    name: hive_db_metastore

networks:
  fbnet-hadoop:
    driver: bridge
    external: True
